### ISSUE TITLE
Vivado script optional no Synthesis

### ISSUE THREAD

**Issue by WRoenninger** [fabianschuiki/bender#23]
`bender script vivado` adds the `TARGET_SYNTHESIS` regardless of test flags.

**Comment by fabianschuiki** [comment]
Do you think @WRoenninger it is a use case to ever use Vivado for purposes other than synthesis?  What's your take on this @accuminium ?

**Comment by accuminium** [comment]
@fabianschuiki Yes, Vivado is also used to simulate designs with Xilinx libraries, either in the embedded simulator or as "proxy" to provide a third-party simulator with the required libraries.  I think we should support this.

Should we add an extra format (e.g., `vivado-sim`) that invokes the existing Vivado TCL emitter (`emit_vivado_tcl`) with different `format_targets` (i.e., `simulation` instead of `synthesis`), or should we add a flag (e.g., `--simulation`) specific to the `vivado` format?

**Comment by fabianschuiki** [comment]
Yeah something like this would be pretty nice!
